"""empty message

Revision ID: d87428f31187
Revises: 4db173b9ed24
Create Date: 2024-07-21 04:17:52.571933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87428f31187'
down_revision = '4db173b9ed24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_venue_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shows_venue_id_fkey', 'Venue', ['venue_id'], ['id'])

    # ### end Alembic commands ###
